language: php

php:
- '7.0'
- '7.1'
- '7.2'
- '7.3'
- '7.4'
- nightly

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

before_script:
- composer install --dev

script: vendor/bin/simple-phpunit
